languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1 # The weight determines the order of languages when building multilingual sites

title = "Shital Shah"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[params.author]
  name = "Shital Shah"
  image = "img/ShitalShah.jpg"
  headline = "If universe is an optimizer, what is its loss function?"
  bio = "Research Engineer at Microsoft Research with interests in deep learning and reinforcement learning. Created AirSim, TensorWatch, archai, most recently worked on Phi series of models."
  links = [
    { email = "mailto:sytelus@yahoo.com" },
    { link = "https://shital.com/" },
    { amazon = "https://www.amazon.com/hz/wishlist/ls/1IGT5ZO7OR6RY" },
    # { apple = "https://www.apple.com" },
    # { blogger = "https://username.blogspot.com/" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    { facebook = "https://facebook.com/sytelus" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/sytelus" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    { google-scholar = "https://scholar.google.com/citations?user=1PEHzesAAAAJ" },
    # { hashnode = "https://username.hashnode.dev" },
    { instagram = "https://instagram.com/sytelus" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://lastfm.com/user/username" },
    { linkedin = "https://linkedin.com/in/shitals" },
    # { mastodon = "https://mastodon.instance/@username" },
    # { medium = "https://medium.com/sytelus" },
    # { mendeley = "https://www.mendeley.com/" },
    # { microsoft = "https://www.microsoft.com/" },
    { orcid = "https://orcid.org/0000-0003-3522-5552" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/sytelus" },
    # { reddit = "https://reddit.com/user/sytelus" },
    # { researchgate = "https://www.researchgate.net/profile/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    { stack-overflow = "https://stackoverflow.com/users/207661/shital-shah" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    # { threads = "https://threads.net/@username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { x-twitter = "https://twitter.com/username" },
    # { youtube = "https://youtube.com/username" },
    # { xing = "https://xing.com/profile/username" },
  ]
