# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Posts
    url: '#posts'
    weight: 10
  - name: About
    url: '#about'
    weight: 100

main_right:
  - name: "<i title=\"Twitter\" class=\"fab fa-twitter\" style=\"font-size:1rem\"></i>"
    post: ""
    url: "https://twitter.com/sytelus"
    weight: 10
  - name: "<i title=\"Google Scholar\" class=\"ai ai-google-scholar\" style=\"font-size:1rem\"></i>"
    post: ""
    url: "https://scholar.google.com/citations?user=1PEHzesAAAAJ"
    weight: 50
  - name: "<i title=\"Stack Overflow\" class=\"fab fa-stack-overflow\" style=\"font-size:1rem\"></i>"
    post: ""
    url: "https://stackoverflow.com/users/207661/shital-shah"
    weight: 60
  - name: "<i title=\"GitHub\" class=\"fab fa-github\" style=\"font-size:1rem\"></i>"
    post: ""
    url: "https://www.github.com/sytelus"
    weight: 40
  - name: "<i title=\"Facebook\" class=\"fab fa-facebook\" style=\"font-size:1rem\"></i>"
    post: ""
    url: "https://www.facebook.com/sytelus"
    weight: 30
  - name: "<i title=\"LinkedIn\" class=\"fab fa-linkedin\" style=\"font-size:1rem\"></i>"
    post: ""
    url: "https://www.linkedin.com/in/shitals"
    weight: 20
  # - name: Posts
  #   url: '#posts'
  #   weight: 20
  # - name: Projects
  #   url: '#projects'
  #   weight: 30
  # - name: Talks
  #   url: '#talks'
  #   weight: 40
  # - name: Publications
  #   url: '#featured'
  #   weight: 50
  # - name: Contact
  #   url: '#contact'
  #   weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
